insert into coordinates (x, y) values (29.9, 56.3);
insert into coordinates (x, y) values (32.8, 14.8);
insert into coordinates (x, y) values (8.4, 99.0);
insert into coordinates (x, y) values (50.1, 19.8);
insert into coordinates (x, y) values (95.6, 3.9);
insert into coordinates (x, y) values (92.1, 42.2);
insert into coordinates (x, y) values (39.5, 60.6);
insert into coordinates (x, y) values (52.7, 39.6);
insert into coordinates (x, y) values (1.9, 13.1);
insert into coordinates (x, y) values (36.8, 17.1);
insert into coordinates (x, y) values (18.8, 35.7);
insert into coordinates (x, y) values (39.6, 31.0);
insert into coordinates (x, y) values (87.2, 46.5);
insert into coordinates (x, y) values (39.5, 16.3);
insert into coordinates (x, y) values (56.2, 58.8);
insert into coordinates (x, y) values (13.1, 68.7);
insert into coordinates (x, y) values (81.8, 57.6);
insert into coordinates (x, y) values (72.2, 99.5);
insert into coordinates (x, y) values (32.6, 20.2);
insert into coordinates (x, y) values (73.8, 90.3);
insert into coordinates (x, y) values (73.8, 60.0);
insert into coordinates (x, y) values (79.5, 86.2);
insert into coordinates (x, y) values (77.8, 63.9);
insert into coordinates (x, y) values (2.9, 74.4);
insert into coordinates (x, y) values (45.0, 29.3);
insert into coordinates (x, y) values (21.2, 93.8);
insert into coordinates (x, y) values (15.7, 86.7);
insert into coordinates (x, y) values (43.4, 91.2);
insert into coordinates (x, y) values (52.9, 48.5);
insert into coordinates (x, y) values (94.8, 91.2);

insert into location (name, x, y) values ('capacity', 41.22, 56.7);
insert into location (name, x, y) values ('empowering', 47.25, 62.6);
insert into location (name, x, y) values ('national', 16.67, 88.8);
insert into location (name, x, y) values ('knowledge user', 9.8, 81.9);
insert into location (name, x, y) values ('uniform', 93.26, 84.3);
insert into location (name, x, y) values ('knowledge user', 29.26, 40.2);
insert into location (name, x, y) values ('open architecture', 62.82, 95.0);
insert into location (name, x, y) values ('Exclusive', 12.93, 38.9);
insert into location (name, x, y) values ('Optional', 31.93, 18.6);
insert into location (name, x, y) values ('installation', 43.86, 53.7);
insert into location (name, x, y) values ('focus group', 71.89, 82.8);
insert into location (name, x, y) values ('instruction set', 9.77, 27.5);
insert into location (name, x, y) values ('synergy', 30.29, 74.9);
insert into location (name, x, y) values ('workforce', 19.3, 53.0);
insert into location (name, x, y) values ('Ameliorated', 69.18, 57.2);
insert into location (name, x, y) values ('static', 78.5, 44.3);
insert into location (name, x, y) values ('alliance', 74.68, 66.2);
insert into location (name, x, y) values ('Business-focused', 34.14, 93.7);
insert into location (name, x, y) values ('disintermediate', 68.85, 97.7);
insert into location (name, x, y) values ('mobile', 37.96, 29.6);
insert into location (name, x, y) values ('bi-directional', 90.13, 54.5);
insert into location (name, x, y) values ('definition', 76.6, 36.2);
insert into location (name, x, y) values ('Graphic Interface', 36.56, 76.0);
insert into location (name, x, y) values ('Open-source', 22.64, 13.0);
insert into location (name, x, y) values ('Customer-focused', 28.92, 30.5);
insert into location (name, x, y) values ('Phased', 73.4, 15.7);
insert into location (name, x, y) values ('6th generation', 35.26, 0.3);
insert into location (name, x, y) values ('infrastructure', 28.37, 65.8);
insert into location (name, x, y) values ('focus group', 15.68, 50.8);
insert into location (name, x, y) values ('fault-tolerant', 38.41, 0.5);

insert into person (name, weight, eyecolor, location_id) values ('secured line', 98, 'YELLOW', 30);
insert into person (name, weight, eyecolor, location_id) values ('Adaptive', 95, 'ORANGE', 2);
insert into person (name, weight, eyecolor, location_id) values ('forecast', 53, 'GREEN', 16);
insert into person (name, weight, eyecolor, location_id) values ('encoding', 91, 'ORANGE', 19);
insert into person (name, weight, eyecolor, location_id) values ('reciprocal', 37, 'YELLOW', 10);
insert into person (name, weight, eyecolor, location_id) values ('complexity', 79, 'RED', 10);
insert into person (name, weight, eyecolor, location_id) values ('framework', 35, 'ORANGE', 26);
insert into person (name, weight, eyecolor, location_id) values ('encoding', 76, 'ORANGE', 27);
insert into person (name, weight, eyecolor, location_id) values ('complexity', 48, 'ORANGE', 10);
insert into person (name, weight, eyecolor, location_id) values ('circuit', 34, 'ORANGE', 8);
insert into person (name, weight, eyecolor, location_id) values ('context-sensitive', 69, 'GREEN', 30);
insert into person (name, weight, eyecolor, location_id) values ('circuit', 99, 'ORANGE', 24);
insert into person (name, weight, eyecolor, location_id) values ('neutral', 77, 'RED', 16);
insert into person (name, weight, eyecolor, location_id) values ('installation', 99, 'GREEN', 12);
insert into person (name, weight, eyecolor, location_id) values ('standardization', 32, 'GREEN', 6);
insert into person (name, weight, eyecolor, location_id) values ('Diverse', 69, 'GREEN', 20);
insert into person (name, weight, eyecolor, location_id) values ('Proactive', 92, 'RED', 14);
insert into person (name, weight, eyecolor, location_id) values ('flexibility', 59, 'RED', 5);
insert into person (name, weight, eyecolor, location_id) values ('zero administration', 62, 'GREEN', 22);
insert into person (name, weight, eyecolor, location_id) values ('monitoring', 82, 'RED', 13);
insert into person (name, weight, eyecolor, location_id) values ('Operative', 99, 'RED', 19);
insert into person (name, weight, eyecolor, location_id) values ('motivating', 50, 'ORANGE', 13);
insert into person (name, weight, eyecolor, location_id) values ('context-sensitive', 36, 'GREEN', 12);
insert into person (name, weight, eyecolor, location_id) values ('systematic', 55, 'YELLOW', 24);
insert into person (name, weight, eyecolor, location_id) values ('pricing structure', 41, 'YELLOW', 23);
insert into person (name, weight, eyecolor, location_id) values ('Customer-focused', 97, 'GREEN', 14);
insert into person (name, weight, eyecolor, location_id) values ('next generation', 82, 'GREEN', 22);
insert into person (name, weight, eyecolor, location_id) values ('interactive', 78, 'GREEN', 12);
insert into person (name, weight, eyecolor, location_id) values ('fresh-thinking', 34, 'GREEN', 22);
insert into person (name, weight, eyecolor, location_id) values ('interactive', 96, 'YELLOW', 2);

insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2020-06-28', 238, 'HORROR', 'NC_17', 'Chrotoem Glasscott', 6, 1, 26);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2002-10-21', 75, 'FANTASY', 'G', 'Mignonne Dunkerley', 2, 2, 16);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2013-05-24', 130, 'TRAGEDY', 'PG_13', 'Shepard Bouchard', 2, 20, 10);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2002-07-04', 213, 'HORROR', 'PG', 'Farrel Jays', 6, 17, 18);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2002-11-29', 179, 'FANTASY', 'NC_17', 'Susy O'' Hanvey', 4, 29, 9);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2005-01-15', 175, 'FANTASY', 'PG_13', 'Corny Vasiliu', 3, 26, 25);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2001-10-28', 44, 'HORROR', 'G', 'Galvan Lyburn', 1, 13, 16);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2019-08-27', 223, 'TRAGEDY', 'NC_17', 'Abbe Cottham', 7, 22, 25);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2008-04-27', 103, 'TRAGEDY', 'PG', 'Herb Deakins', 2, 13, 19);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2004-01-29', 89, 'HORROR', 'G', 'Shaun Mainz', 5, 7, 21);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2005-01-10', 154, 'FANTASY', 'PG_13', 'Leontyne Ambrois', 1, 6, 3);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2005-08-04', 206, 'TRAGEDY', 'R', 'Mario Wittey', 4, 10, 8);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2016-12-13', 240, 'TRAGEDY', 'PG_13', 'Carney Twentyman', 3, 30, 17);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2013-08-15', 65, 'FANTASY', 'G', 'Faulkner Dablin', 4, 27, 15);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2021-06-08', 236, 'HORROR', 'G', 'Willy Piris', 0, 4, 23);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2012-10-10', 178, 'FANTASY', 'G', 'Ashleigh Woolerton', 7, 12, 21);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2001-03-21', 205, 'DRAMA', 'R', 'Granny Mahony', 2, 13, 25);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2002-07-14', 145, 'HORROR', 'PG_13', 'Maggie Fergyson', 7, 28, 10);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2012-01-24', 182, 'HORROR', 'R', 'Fabian Pocknell', 6, 4, 21);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2007-04-02', 142, 'FANTASY', 'R', 'Brenden Itzhaiek', 1, 24, 21);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2017-11-22', 146, 'HORROR', 'NC_17', 'Janette Ornils', 3, 23, 4);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2008-02-25', 163, 'TRAGEDY', 'PG', 'Vivie Jewer', 0, 28, 18);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2016-05-16', 175, 'TRAGEDY', 'NC_17', 'Jess Gyles', 3, 14, 15);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2009-09-08', 241, 'FANTASY', 'NC_17', 'Georgette Bamford', 7, 5, 17);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2007-07-16', 53, 'TRAGEDY', 'R', 'Quintin Heckle', 3, 19, 25);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2021-07-16', 247, 'FANTASY', 'PG_13', 'Aurilia FitzAlan', 1, 20, 25);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2018-02-07', 165, 'FANTASY', 'R', 'Orelie Lory', 0, 30, 26);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2014-04-21', 205, 'TRAGEDY', 'R', 'Gregory Wieprecht', 2, 21, 28);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2001-05-07', 239, 'DRAMA', 'NC_17', 'Julie Edward', 0, 9, 2);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2015-11-06', 244, 'TRAGEDY', 'PG', 'Kimball Frazier', 1, 14, 16);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2019-05-20', 226, 'TRAGEDY', 'G', 'Arnaldo Liddington', 8, 13, 6);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2021-04-03', 110, 'DRAMA', 'G', 'Kincaid Westbury', 6, 22, 17);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2007-05-19', 126, 'DRAMA', 'PG_13', 'Amandy Rickerd', 5, 19, 28);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2018-06-10', 67, 'DRAMA', 'G', 'Nissy Bardwall', 3, 20, 30);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2001-05-15', 219, 'FANTASY', 'NC_17', 'Jeanelle Boler', 2, 20, 26);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2018-04-11', 188, 'HORROR', 'R', 'Rosie Wayman', 2, 16, 8);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2016-04-21', 35, 'FANTASY', 'PG_13', 'Julieta Zute', 1, 23, 22);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2015-01-12', 54, 'HORROR', 'R', 'Dorice Chettle', 7, 11, 16);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2013-10-16', 203, 'FANTASY', 'PG_13', 'Odella Gottschalk', 2, 26, 25);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2021-03-12', 211, 'HORROR', 'R', 'Lowe Stephenson', 5, 23, 11);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2020-03-20', 238, 'FANTASY', 'NC_17', 'Ody MacAlinden', 2, 18, 28);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2017-05-02', 191, 'TRAGEDY', 'NC_17', 'Jody Askin', 7, 14, 5);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2001-12-23', 179, 'DRAMA', 'NC_17', 'Shem Ibert', 0, 24, 28);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2008-09-17', 224, 'TRAGEDY', 'R', 'Aveline Strickland', 1, 12, 21);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2005-10-31', 214, 'TRAGEDY', 'NC_17', 'Roy Blakemore', 2, 3, 29);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2003-04-12', 78, 'DRAMA', 'PG', 'Lucky McKeighan', 0, 18, 11);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2017-10-20', 170, 'DRAMA', 'G', 'Goober Southan', 5, 19, 30);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2001-04-23', 86, 'TRAGEDY', 'NC_17', 'Allianora Georgeon', 5, 19, 13);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2013-09-29', 211, 'FANTASY', 'NC_17', 'Hewe O''Gavin', 8, 15, 27);
insert into movie (date, duration, genre, rating, name, oscars, coordinate_id, person_id) values ('2017-01-14', 194, 'DRAMA', 'G', 'Jard Wones', 3, 21, 7);